[r]
ngrid = 1
nelement = 1

[evolve_moments]
density = false
moments_conservation = false
parallel_flow = false
pressure = false

[ion_species_1]
initial_temperature = 0.3333333333333333
initial_density = 55.0

[krook_collisions]
use_krook = true
frequency_option = "reference_parameters"

[vpa]
ngrid = 6
discretization = "chebyshev_pseudospectral"
nelement = 43
L = 33.941125496954285
element_spacing_option = "coarse_tails7.0710678118654755"
bc = "zero"

[z]
ngrid = 5
discretization = "chebyshev_pseudospectral"
nelement = 32
bc = "wall"

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[composition]
T_e = 0.8
electron_physics = "boltzmann_electron_response"
n_ion_species = 1
n_neutral_species = 0

[ion_source_2]
source_T = 0.1
active = true
source_strength = 77.78174593052023
z_profile = "wall_exp_decay"
z_width = 0.15

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 1.4142135623730951
temperature_phase = 0.0
upar_phase = 0.0

[ion_source_1]
PI_temperature_controller_I = 150.0
z_width = 0.275816
source_T = 1.5
active = true
PI_temperature_target_amplitude = 0.3333333333333333
source_strength = 77.78174593052023
z_profile = "super_gaussian_4"
PI_temperature_controller_P = 106.06601717798213
source_type = "temperature_midpoint_control"

[timestepping]
nstep = 25000
steady_state_residual = true
dt = 0.0007071067811865475
nwrite = 500
type = "SSPRK4"
nwrite_dfns = 500
