test_type = "Harrison-Thompson wall boundary condition"

# default inputs for tests
test_input_finite_difference = Dict("n_ion_species" => 2,
                                    "n_neutral_species" => 2,
                                    "boltzmann_electron_response" => true,
                                    "run_name" => "finite_difference",
                                    "base_directory" => test_output_directory,
                                    "evolve_moments_density" => false,
                                    "evolve_moments_parallel_flow" => false,
                                    "evolve_moments_parallel_pressure" => false,
                                    "evolve_moments_conservation" => false,
                                    "T_e" => 1.0,
                                    "T_wall" => 1.0,
                                    "initial_density1" => 1.0,
                                    "initial_temperature1" => 1.0,
                                    "z_IC_option1" => "gaussian",
                                    "z_IC_density_amplitude1" => 0.001,
                                    "z_IC_density_phase1" => 0.0,
                                    "z_IC_upar_amplitude1" => 0.0,
                                    "z_IC_upar_phase1" => 0.0,
                                    "z_IC_temperature_amplitude1" => 0.0,
                                    "z_IC_temperature_phase1" => 0.0,
                                    "vpa_IC_option1" => "gaussian",
                                    "vpa_IC_density_amplitude1" => 1.0,
                                    "vpa_IC_density_phase1" => 0.0,
                                    "vpa_IC_upar_amplitude1" => 0.0,
                                    "vpa_IC_upar_phase1" => 0.0,
                                    "vpa_IC_temperature_amplitude1" => 0.0,
                                    "vpa_IC_temperature_phase1" => 0.0,
                                    "charge_exchange_frequency" => 0.0,
                                    #"ionization_frequency" => 0.25,
                                    "ionization_frequency" => 0.688,
                                    "constant_ionization_rate" => true,
                                    "nstep" => 3,
                                    "dt" => 0.0005,
                                    "nwrite" => 2,
                                    "use_semi_lagrange" => false,
                                    "n_rk_stages" => 2,
                                    "split_operators" => false,
                                    "z_ngrid" => 4,
                                    "z_nelement" => 1,
                                    "z_bc" => "periodic",
                                    "z_discretization" => "finite_difference",
                                    "vpa_ngrid" => 4,
                                    "vpa_nelement" => 1,
                                    "vpa_L" => 8.0,
                                    "vpa_bc" => "periodic",
                                    "vpa_discretization" => "finite_difference",
                                    "vperp_ngrid" => 1,
                                    "vperp_nelement" => 1,
                                    "vz_ngrid" => 4,
                                    "vz_nelement" => 1,
                                    "vz_L" => 8.0,
                                    "vz_bc" => "periodic",
                                    "vz_discretization" => "finite_difference",
                                    "vzeta_ngrid" => 1,
                                    "vzeta_nelement" => 1,
                                    "vr_ngrid" => 1,
                                    "vr_nelement" => 1)

test_input_chebyshev = merge(test_input_finite_difference,
                             Dict("run_name" => "chebyshev_pseudospectral",
                                  "z_discretization" => "chebyshev_pseudospectral",
                                  "z_ngrid" => 3,
                                  "z_nelement" => 2,
                                  "vpa_discretization" => "chebyshev_pseudospectral",
                                  "vpa_ngrid" => 3,
                                  "vpa_nelement" => 2,
                                  "vz_discretization" => "chebyshev_pseudospectral",
                                  "vz_ngrid" => 3,
                                  "vz_nelement" => 2))

test_input_list = [
     test_input_finite_difference,
     test_input_chebyshev,
    ]
