[r]
ngrid = 1
nelement = 1

[z]
ngrid = 81
nelement = 1
bc = "periodic"
discretization = "finite_difference"

[vpa]
ngrid = 241
nelement = 1
L = 11.313708498984761
bc = "periodic"
discretization = "finite_difference"

[timestepping]
nstep = 100
dt = 0.00035355339059327376
nwrite = 100000000
n_rk_stages = 4
split_operators = false


[output]
base_directory = "value"

[evolve_moments]
pressure = false
density = false
moments_conservation = true
parallel_flow = false

[ion_species_1]
initial_temperature = 0.3333333333333333
initial_density = 0.5

[reactions]
charge_exchange_frequency = 0.8885765876316732

[z_IC_neutral_species_1]
density_amplitude = 0.5
temperature_amplitude = 0.5
density_phase = 3.141592653589793
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[composition]
T_e = 1.0
n_ion_species = 1
n_neutral_species = 1

[z_IC_ion_species_1]
density_amplitude = 0.5
temperature_amplitude = 0.5
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 3.141592653589793
upar_phase = 0.0

[neutral_species_1]
initial_temperature = 0.3333333333333333
initial_density = 0.5
