[z]
ngrid = 9
nelement = 10
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 17
nelement = 15
L = 13.856406460551018
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 100
dt = 0.00035355339059327376
nwrite = 200
n_rk_stages = 4
split_operators = false


[output]
base_directory = "value"

[evolve_moments]
pressure = true
density = true
moments_conservation = true
parallel_flow = true

[ion_species_1]
initial_temperature = 0.3333333333333333
initial_density = 0.5

[reactions]
ionization_frequency = 0.0
charge_exchange_frequency = 0.8885765876316732

[z_IC_neutral_species_1]
density_amplitude = 0.5
temperature_amplitude = 0.5
density_phase = 3.141592653589793
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[composition]
T_e = 1.0
n_ion_species = 1
n_neutral_species = 1

[z_IC_ion_species_1]
density_amplitude = 0.5
temperature_amplitude = 0.5
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 3.141592653589793
upar_phase = 0.0

[neutral_species_1]
initial_temperature = 0.3333333333333333
initial_density = 0.5
