steady_state_residual = true
converged_residual_value = 1.0e-3
#runtime_plots = true
charge_exchange_frequency = 0.75
ionization_frequency = 0.5
constant_ionization_rate = false

[evolve_moments]
density = true
parallel_flow = true
parallel_pressure = false
moments_conservation = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 9
nelement = 32
#nelement_local = 4
bc = "wall"
discretization = "chebyshev_pseudospectral"
element_spacing_option = "sqrt"

[vpa]
ngrid = 10
nelement = 63
L = 18.0
bc = "zero"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 10
nelement = 63
L = 18.0
bc = "zero"
discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
recycling_fraction = 0.25
T_e = 0.2 # 1.0
T_wall = 0.1

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = -1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
nstep = 1000000
dt = 3.0e-5
nwrite = 10000
nwrite_dfns = 10000
split_operators = false

[ion_source]
active = true
z_profile = "gaussian"
z_width = 0.125
source_strength = 2.0
source_T = 2.0

[neutral_source]
active = true
source_type = "recycling"
recycling_controller_fraction = 0.25

[ion_numerical_dissipation]
#vpa_dissipation_coefficient = 1.0e-1
#vpa_dissipation_coefficient = 1.0e-2
#vpa_dissipation_coefficient = 1.0e-3
#force_minimum_pdf_value = 0.0

[neutral_numerical_dissipation]
#vz_dissipation_coefficient = 1.0e-1
#vz_dissipation_coefficient = 1.0e-2
#vz_dissipation_coefficient = 1.0e-3
#force_minimum_pdf_value = 0.0

[krook_collisions]
use_krook = true
frequency_option = "reference_parameters"
