steady_state_residual = true
converged_residual_value = 1.0e-3
runtime_plots = true
evolve_moments_density = true
evolve_moments_parallel_flow = true
evolve_moments_parallel_pressure = true
evolve_moments_conservation = true
r_ngrid = 1
r_nelement = 1
z_ngrid = 9
z_nelement = 32
#z_nelement_local = 4
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 10
vpa_nelement = 63
vpa_L = 18.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
vz_ngrid = 10
vz_nelement = 63
vz_L = 18.0
vz_bc = "zero"
vz_discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 0
electron_physics = "boltzmann_electron_response"
recycling_fraction = 0.5
T_e = 0.2 # 1.0
T_wall = 0.1

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
nstep = 100000
dt = 1.0e-4
nwrite = 5000
nwrite_dfns = 5000
split_operators = false

[ion_source]
active = true
z_profile = "gaussian"
z_width = 0.125
source_strength = 8.0
source_T = 1.0

[ion_numerical_dissipation]
#vpa_dissipation_coefficient = 1.0e-1
#vpa_dissipation_coefficient = 1.0e-2
#vpa_dissipation_coefficient = 1.0e-3
force_minimum_pdf_value = 0.0

[krook_collisions]
use_krook = true
frequency_option = "reference_parameters"