evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
charge_exchange_frequency = 0.75
ionization_frequency = 0.5
constant_ionization_rate = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 5
nelement = 32
nelement_local = 16
bc = "wall"
discretization = "chebyshev_pseudospectral"
element_spacing_option = "sqrt"

[vpa]
ngrid = 6
nelement = 63
L = 36.0
bc = "zero"
discretization = "chebyshev_pseudospectral"
element_spacing_option = "coarse_tails"

[vz]
ngrid = 6
nelement = 63
L = 36.0
bc = "zero"
discretization = "chebyshev_pseudospectral"
element_spacing_option = "coarse_tails"

[composition]
n_ion_species = 1
n_neutral_species = 1
recycling_fraction = 0.5
T_e = 0.2 # 1.0
T_wall = 0.1

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = -1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
type = "Fekete4(3)"
nstep = 10000000
dt = 1.0e-5
minimum_dt = 1.0e-6
nwrite = 10000
nwrite_dfns = 10000
split_operators = false
steady_state_residual = true
converged_residual_value = 1.0e-3

[krook_collisions]
use_krook = true

[ion_source]
active = true
z_profile = "gaussian"
z_width = 0.125
source_strength = 2.0
source_T = 2.0

[ion_numerical_dissipation]
#vpa_dissipation_coefficient = 1.0e-1
#vpa_dissipation_coefficient = 1.0e-2
#vpa_dissipation_coefficient = 1.0e-3

[neutral_numerical_dissipation]
#vz_dissipation_coefficient = 1.0e-1
#vz_dissipation_coefficient = 1.0e-2
#vz_dissipation_coefficient = 1.0e-3
