#runtime_plots = true
evolve_moments_density = true
evolve_moments_parallel_flow = true
evolve_moments_parallel_pressure = true
evolve_moments_conservation = true
charge_exchange_frequency = 0.75
ionization_frequency = 0.5
constant_ionization_rate = false
r_ngrid = 1
r_nelement = 1
z_ngrid = 9
z_nelement = 32
z_nelement_local = 16
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
z_element_spacing_option = "sqrt"
vpa_ngrid = 10
vpa_nelement = 63
vpa_L = 36.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
vpa_element_spacing_option = "coarse_tails"
vz_ngrid = 10
vz_nelement = 63
vz_L = 36.0
vz_bc = "zero"
vz_discretization = "chebyshev_pseudospectral"
vz_element_spacing_option = "coarse_tails"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
recycling_fraction = 0.5
T_e = 0.2 # 1.0
T_wall = 0.1

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = -1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_neutral_species_1]
initialization_option= "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
type = "Fekete6(4)"
#nstep = 50000
nstep = 1000000
dt = 1.0e-5
#minimum_dt = 1.0e-8
minimum_dt = 1.0e-6
step_update_prefactor = 0.5
atol = 1.0e-10
#atol = 1.0e-9
nwrite = 10000
nwrite_dfns = 10000
split_operators = false
steady_state_residual = true
converged_residual_value = 1.0e-3

[krook_collisions]
use_krook = true

[ion_source_1]
active = true
z_profile = "gaussian"
z_width = 0.125
source_strength = 2.0
source_T = 2.0

[numerical_dissipation]
#vz_dissipation_coefficient = 1.0e-1
#vz_dissipation_coefficient = 1.0e-2
#vz_dissipation_coefficient = 1.0e-3
force_minimum_pdf_value = 0.0
