#use_manufactured_solns_for_init = true
#use_manufactured_solns_for_advance = false
n_ion_species = 1
n_neutral_species = 0
electron_physics = "boltzmann_electron_response"
#electron_physics = "boltzmann_electron_response_with_simple_sheath"
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
#force_Er_zero_at_wall = false #true
#Er_constant = 0.0
#epsilon_offset = 0.1
#use_vpabar_in_mms_dfni = true
T_e = 1.0
T_wall = 1.0
rhostar = 1.0
Bzed = 1.0
Bmag = 1.0
initial_density1 = 0.5
initial_temperature1 = 1.0
initial_density2 = 0.5
initial_temperature2 = 1.0
z_IC_option1 = "sinusoid"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
z_IC_option2 = "sinusoid"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.0
ionization_frequency = 0.0
constant_ionization_rate = false
nuii = 1.0
#nuii_krook = 0.0
#nuii_pitch = 0.0
nstep = 5000
dt = 1.0e-2
nwrite = 5000
nwrite_dfns = 5000
use_semi_lagrange = false
n_rk_stages = 4
split_operators = false
z_ngrid = 1
z_nelement = 1
z_nelement_local = 1
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
r_ngrid = 1
r_nelement = 1
r_nelement_local = 1
r_bc = "periodic"
r_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 3
vpa_nelement = 6
vpa_L = 6.0
vpa_bc = "zero"
#vpa_discretization = "chebyshev_pseudospectral"
vpa_discretization = "gausslegendre_pseudospectral"
vperp_ngrid = 3
vperp_nelement = 3
vperp_L = 3.0
#vperp_discretization = "finite_difference"
#vperp_discretization = "chebyshev_pseudospectral"
vperp_discretization = "gausslegendre_pseudospectral"

#vz_ngrid = 17
#vz_nelement = 4
#vz_L = 12.0
#vz_bc = "periodic"
#vz_discretization = "chebyshev_pseudospectral"

#vr_ngrid = 17
#vr_nelement = 4
#vr_L = 12.0
#vr_bc = "periodic"
#vr_discretization = "chebyshev_pseudospectral"

#vzeta_ngrid = 17
#vzeta_nelement = 4
#vzeta_L = 12.0
#vzeta_bc = "periodic"
#vzeta_discretization = "chebyshev_pseudospectral"

#[ion_numerical_dissipation]
#vpa_dissipation_coefficient = 0.0
#vperp_dissipation_coefficient = 0.0
#z_dissipation_coefficient = 0.1
#r_dissipation_coefficient = 0.0
