[r]
ngrid = 1
nelement = 1

[evolve_moments]
density = true
moments_conservation = true
parallel_flow = true
pressure = true

[ion_species_1]
initial_temperature = 0.3333333333333333
initial_density = 3.0

[krook_collisions]
use_krook = true
frequency_option = "reference_parameters"
nuii0 = 1.4142135623730951

[vpa]
ngrid = 6
discretization = "chebyshev_pseudospectral"
nelement = 63
L = 62.35382907247958
bc = "zero"
element_spacing_option = "coarse_tails8.660254037844386"

[z]
ngrid = 5
discretization = "chebyshev_pseudospectral"
#element_spacing_option = "sqrt"
nelement = 32
bc = "wall"

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

#[z_IC_neutral_species_1]
#initialization_option = "gaussian"
#temperature_amplitude = 0.0
#density_amplitude = 0.001
#density_phase = 0.0
#upar_amplitude = -1.0
#temperature_phase = 0.0
#upar_phase = 0.0

[composition]
#T_wall = 0.1
T_e = 0.5
electron_physics = "boltzmann_electron_response"
n_ion_species = 1
n_neutral_species = 0
#ion_physics = "coll_krook_ions"

#[vz_IC_neutral_species_1]
#initialization_option = "gaussian"
#density_amplitude = 1.0
#temperature_amplitude = 0.0
#density_phase = 0.0
#upar_amplitude = 0.0
#temperature_phase = 0.0
#upar_phase = 0.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 1.4142135623730951
temperature_phase = 0.0
upar_phase = 0.0

#[neutral_species_1]
#initial_temperature = 1.0
#initial_density = 1.0

[ion_source_1]
source_T = 1.0
active = true
source_strength = 4.242640687119286
source_type = "energy"
z_profile = "super_gaussian_4"
z_width = 0.275816

[ion_source_2]
source_T = 0.1
active = true
source_strength = 7.0710678118654755
z_profile = "wall_exp_decay"
z_width = 0.15

[timestepping]
nstep = 8000
steady_state_residual = true
dt = 7.071067811865475e-5
nwrite = 1000
type = "SSPRK4"
nwrite_dfns = 1000
