evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = true
charge_exchange_frequency = 0.62831853071
ionization_frequency = 0.0
r_ngrid = 1
r_nelement = 1
z_ngrid = 9
z_nelement = 2
z_bc = "periodic"
z_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 17
vpa_nelement = 8
vpa_L = 8.0
vpa_bc = "periodic"
vpa_discretization = "chebyshev_pseudospectral"
vz_ngrid = 17
vz_nelement = 8
vz_L = 8.0
vz_bc = "periodic"
vz_discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
T_e = 1.0

[ion_species_1]
initial_density = 0.5
initial_temperature = 1.0

[neutral_species_1]
initial_density = 0.5
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[output]
binary_format = "netcdf"

[timestepping]
nstep = 1500
dt = 0.002
nwrite = 20
split_operators = false
