[reactions]
charge_exchange_frequency = 0.62831853071
ionization_frequency = 0.0

[evolve_moments]
density = false
parallel_flow = false
parallel_pressure = false
moments_conservation = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 100
nelement = 1
bc = "periodic"
discretization = "finite_difference"

[vpa]
ngrid = 180
nelement = 1
L = 8.0
bc = "periodic"
discretization = "finite_difference"

[vz]
ngrid = 180
nelement = 1
L = 8.0
bc = "periodic"
discretization = "finite_difference"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
T_e = 1.0

[ion_species_1]
initial_density = 0.5
initial_temperature = 1.0

[neutral_species_1]
initial_density = 0.5
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
nstep = 1500
dt = 0.002
nwrite = 20
split_operators = false
