[evolve_moments]
density = true
parallel_flow = true
pressure = true

[krook_collisions]
use_krook = true

[composition]
T_e = 1.0
n_ion_species = 1
n_neutral_species = 0

[ion_source_1]
active = true
z_profile = "gaussian"
z_width = 0.1
source_strength = 10.0
source_T = 3.0

[reference_params]
Bref = 1.0
Lref = 20.0
Nref = 1.0e19
Tref = 100.0

[z]
ngrid = 5
discretization = "chebyshev_pseudospectral"
nelement = 128
#nelement_local = 2
L = 1.0
element_spacing_option = "sqrt"
bc = "wall"

[vpa]
ngrid = 5
discretization = "chebyshev_pseudospectral"
nelement = 128
L = 40.0
element_spacing_option = "coarse_tails4"
bc = "zero"

[ion_species_1]
initial_temperature = 0.33333333333333333333333
initial_density = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 1.0
temperature_phase = 0.0
upar_phase = 0.0

[timestepping]
type = "Fekete4(3)"
nstep = 1000000000
dt = 1.0e-6
minimum_dt = 1.0e-6
#maximum_dt = 1.0e-4
max_increase_factor = 1.001
rtol = 1.0e-5
atol = 1.0e-11
step_update_prefactor = 0.1
nwrite = 1000000
nwrite_dfns = 1000000
steady_state_residual = true
converged_residual_value = 1.0e-6

[ion_numerical_dissipation]
force_minimum_pdf_value = 0.0
