[r]
ngrid = 1
nelement = 1

[evolve_moments]
density = false
moments_conservation = false
parallel_flow = false
pressure = false

[ion_species_1]
initial_temperature = 0.3333333333333333
initial_density = 1.0

[krook_collisions]
use_krook = true
frequency_option = "reference_parameters"
nuii0 = 1.4142135623730951

[vpa]
ngrid = 6
discretization = "chebyshev_pseudospectral"
nelement = 63
L = 50.91168824543143
bc = "zero"

[z]
ngrid = 5
discretization = "chebyshev_pseudospectral"
nelement = 32
bc = "wall"

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
temperature_amplitude = 0.0
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = -1.4142135623730951
temperature_phase = 0.0
upar_phase = 0.0

[composition]
T_wall = 0.1
T_e = 0.2
electron_physics = "boltzmann_electron_response"
n_ion_species = 1
n_neutral_species = 0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[ion_source_2]
source_T = 0.2
active = true
source_strength = 0.7071067811865476
z_profile = "wall_exp_decay"
z_width = 0.1

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 1.4142135623730951
temperature_phase = 0.0
upar_phase = 0.0

[neutral_species_1]
initial_temperature = 0.3333333333333333
initial_density = 1.0

[ion_source_1]
source_T = 2.0
active = true
source_strength = 2.8284271247461903
z_profile = "gaussian"
z_width = 0.3

[timestepping]
nstep = 1000
steady_state_residual = true
dt = 0.000565685424949238
nwrite = 100
type = "SSPRK4"
nwrite_dfns = 100
