#runtime_plots = true
n_ion_species = 1
n_neutral_species = 1
electron_physics = "kinetic_electrons"
evolve_moments_density = true
evolve_moments_parallel_flow = true
evolve_moments_parallel_pressure = true
evolve_moments_conservation = true
recycling_fraction = 0.5
T_e = 1.0
T_wall = 0.1
initial_density1 = 1.0
initial_temperature1 = 1.0
z_IC_option1 = "sinusoid"
z_IC_density_amplitude1 = 0.1
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 1.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.1
z_IC_temperature_phase1 = 1.0
vpa_IC_option1 = "gaussian"
vpa_IC_density_amplitude1 = 1.0
vpa_IC_density_phase1 = 0.0
vpa_IC_upar_amplitude1 = 0.0
vpa_IC_upar_phase1 = 0.0
vpa_IC_temperature_amplitude1 = 0.0
vpa_IC_temperature_phase1 = 0.0
initial_density2 = 1.0
initial_temperature2 = 1.0
z_IC_option2 = "sinusoid"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
vpa_IC_option2 = "gaussian"
vpa_IC_density_amplitude2 = 1.0
vpa_IC_density_phase2 = 0.0
vpa_IC_upar_amplitude2 = 0.0
vpa_IC_upar_phase2 = 0.0
vpa_IC_temperature_amplitude2 = 0.0
vpa_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.75
ionization_frequency = 0.0
constant_ionization_rate = false
nu_ei = 1000.0
r_ngrid = 1
r_nelement = 1
z_ngrid = 17
z_nelement = 16
#z_nelement_local = 16
z_bc = "periodic"
z_discretization = "chebyshev_pseudospectral"
vpa_ngrid = 6
vpa_nelement = 31
vpa_L = 12.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
vz_ngrid = 6
vz_nelement = 31
vz_L = 12.0
vz_bc = "zero"
vz_discretization = "chebyshev_pseudospectral"

[reference_params]
Tref = 20.0

[timestepping]
#type = "KennedyCarpenterARK324"
type = "Fekete4(3)"
implicit_ion_advance = false
implicit_vpa_advection = false
nstep = 1000000
dt = 1.0e-6
minimum_dt = 1.0e-7
rtol = 1.0e-7
max_increase_factor_near_last_fail = 1.001
last_fail_proximity_factor = 1.1
max_increase_factor = 1.05
nwrite = 10000
nwrite_dfns = 100000
steady_state_residual = true
converged_residual_value = 1.0e-3
#[timestepping]
##type = "KennedyCarpenterARK324"
#type = "Fekete4(3)"
#implicit_ion_advance = false
#implicit_vpa_advection = false
#nstep = 1000000
#dt = 1.0e-6
#minimum_dt = 1.0e-7
#rtol = 1.0e-7
#max_increase_factor_near_last_fail = 1.001
#last_fail_proximity_factor = 1.1
#max_increase_factor = 1.05
#nwrite = 100
#nwrite_dfns = 100
#steady_state_residual = true
#converged_residual_value = 1.0e-3
#write_after_fixed_step_count = true
#write_error_diagnostics = true
#write_steady_state_diagnostics = true

[electron_timestepping]
nstep = 5000000
#nstep = 1
dt = 2.0e-8
maximum_dt = 1.0
nwrite = 10000
nwrite_dfns = 100000
#type = "SSPRK4"
type = "Fekete4(3)"
rtol = 1.0e-6
atol = 1.0e-14
minimum_dt = 1.0e-10
initialization_residual_value = 2.5
converged_residual_value = 0.1 #1.0e-3
#debug_io = 10000

[ion_numerical_dissipation]
vpa_dissipation_coefficient = 1.0e0
force_minimum_pdf_value = 0.0

[electron_numerical_dissipation]
vpa_dissipation_coefficient = 2.0e0
force_minimum_pdf_value = 0.0

[neutral_numerical_dissipation]
vz_dissipation_coefficient = 1.0e-1
force_minimum_pdf_value = 0.0

[krook_collisions]
use_krook = true
