[reactions]
charge_exchange_frequency = 1.0606601717798214
ionization_frequency = 0.0

[evolve_moments]
density = true
parallel_flow = true
moments_conservation = true
pressure = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 17
nelement = 16
#nelement_local = 16
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 6
nelement = 31
L = 20.784609690826528
bc = "zero"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 6
nelement = 31
L = 20.784609690826528
bc = "zero"
discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
recycling_fraction = 0.5
T_e = 1.0
T_wall = 0.1

[ion_species_1]
initial_density = 1.0
initial_temperature = 0.3333333333333333

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.1
density_phase = 0.0
upar_amplitude = 1.4142135623730951
upar_phase = 0.0
temperature_amplitude = 0.1
temperature_phase = 1.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 0.3333333333333333

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[timestepping]
type = "Fekete4(3)"
nstep = 1000000
dt = 7.071067811865475e-7
minimum_dt = 7.071067811865474e-8
rtol = 1.0e-7
nwrite = 10000
nwrite_dfns = 100000
steady_state_residual = true
converged_residual_value = 0.0014142135623730952

[nonlinear_solver]
nonlinear_max_iterations = 100
#rtol = 1.0e-9
#atol = 1.0e-12

[ion_numerical_dissipation]
vpa_dissipation_coefficient = 4.242640687119286
force_minimum_pdf_value = 0.0

[neutral_numerical_dissipation]
vz_dissipation_coefficient = 0.42426406871192857
force_minimum_pdf_value = 0.0

[krook_collisions]
use_krook = true
