[reactions]
charge_exchange_frequency = 0.75
ionization_frequency = 0.0

[evolve_moments]
density = true
parallel_flow = true
parallel_pressure = true
moments_conservation = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 5
nelement = 32
#nelement_local = 16
bc = "periodic"
discretization = "gausslegendre_pseudospectral"

[vpa]
ngrid = 6
nelement = 31
L = 12.0
bc = "zero"
discretization = "gausslegendre_pseudospectral"

[vz]
ngrid = 6
nelement = 31
L = 12.0
bc = "zero"
discretization = "gausslegendre_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "kinetic_electrons"
recycling_fraction = 0.5
T_e = 1.0
T_wall = 0.1

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.1
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.1
temperature_phase = 1.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0

[reference_params]
Tref = 20.0

[timestepping]
#type = "KennedyCarpenterARK324"
type = "Fekete4(3)"
kinetic_electron_solver = "explicit_pseudotimestep"
kinetic_ion_solver = "full_explicit_ion_advance"
nstep = 1000000
dt = 1.0e-6
minimum_dt = 1.0e-7
rtol = 1.0e-7
max_increase_factor_near_last_fail = 1.001
last_fail_proximity_factor = 1.1
max_increase_factor = 1.05
nwrite = 10000
nwrite_dfns = 100000
steady_state_residual = true
converged_residual_value = 1.0e-3
#[timestepping]
##type = "KennedyCarpenterARK324"
#type = "Fekete4(3)"
#kinetic_ion_solver = "full_explicit_ion_advance"
#nstep = 1000000
#dt = 1.0e-6
#minimum_dt = 1.0e-7
#rtol = 1.0e-7
#max_increase_factor_near_last_fail = 1.001
#last_fail_proximity_factor = 1.1
#max_increase_factor = 1.05
#nwrite = 100
#nwrite_dfns = 100
#steady_state_residual = true
#converged_residual_value = 1.0e-3
#write_after_fixed_step_count = true
#write_error_diagnostics = true
#write_steady_state_diagnostics = true

[electron_timestepping]
nstep = 5000000
#nstep = 1
dt = 2.0e-8
maximum_dt = 1.0
nwrite = 10000
nwrite_dfns = 100000
#type = "SSPRK4"
type = "Fekete4(3)"
rtol = 1.0e-6
atol = 1.0e-14
minimum_dt = 1.0e-10
decrease_dt_iteration_threshold = 100
increase_dt_iteration_threshold = 20
cap_factor_ion_dt = 10.0
initialization_residual_value = 2.5
converged_residual_value = 0.1 #1.0e-3
#debug_io = 10000

[ion_numerical_dissipation]
vpa_dissipation_coefficient = 1.0e0
force_minimum_pdf_value = 0.0

[electron_numerical_dissipation]
vpa_dissipation_coefficient = 2.0e0
force_minimum_pdf_value = 0.0

[neutral_numerical_dissipation]
vz_dissipation_coefficient = 1.0e-1
force_minimum_pdf_value = 0.0

[krook_collisions]
use_krook = true
