[r]
ngrid = 1
nelement = 1

[evolve_moments]
density = true
moments_conservation = true
parallel_flow = true
pressure = true

[reactions]
electron_ionization_frequency = 0.0
ionization_frequency = 0.7071067811865476
charge_exchange_frequency = 1.0606601717798214

[vz]
ngrid = 6
discretization = "gausslegendre_pseudospectral"
nelement = 31
L = 62.35382907247958
element_spacing_option = "coarse_tails8.660254037844386"
bc = "zero"

[ion_species_1]
initial_temperature = 0.03333333333333333
initial_density = 1.0

[krook_collisions]
use_krook = true

[vpa]
ngrid = 6
discretization = "gausslegendre_pseudospectral"
nelement = 31
L = 51.96152422706631
element_spacing_option = "coarse_tails8.660254037844386"
bc = "zero"

[z]
ngrid = 5
discretization = "gausslegendre_pseudospectral"
nelement = 32
#nelement_local = 16
bc = "wall"

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
temperature_amplitude = 0.0
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = -1.4142135623730951
temperature_phase = 0.0
upar_phase = 0.0

[composition]
T_wall = 0.1
T_e = 0.2
recycling_fraction = 0.5
n_ion_species = 1
n_neutral_species = 1

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
temperature_phase = 0.0
upar_phase = 0.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
temperature_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 1.4142135623730951
temperature_phase = 0.0
upar_phase = 0.0

[neutral_species_1]
initial_temperature = 0.3333333333333333
initial_density = 1.0

[timestepping]
type = "Fekete4(3)"
nstep = 10000000
dt = 7.0710678118654756e-6
minimum_dt = 7.071067811865475e-7
#maximum_dt = 5.0e-5
rtol = 1.0e-5
atol = 1.0e-12
nwrite = 25000
nwrite_dfns = 25000
steady_state_residual = true
converged_residual_value = 0.0014142135623730952

[ion_source_1]
active = true
z_profile = "gaussian"
z_width = 0.125
source_strength = 2.8284271247461903
source_T = 2.0

[ion_numerical_dissipation]
#vpa_dissipation_coefficient = 1.0e-1
#vpa_dissipation_coefficient = 1.0e-2
#vpa_dissipation_coefficient = 1.0e-3
force_minimum_pdf_value = 0.0

[electron_numerical_dissipation]
#vpa_dissipation_coefficient = 2.0
force_minimum_pdf_value = 0.0

[neutral_numerical_dissipation]
#vz_dissipation_coefficient = 1.0e-1
#vz_dissipation_coefficient = 1.0e-2
#vz_dissipation_coefficient = 1.0e-3
force_minimum_pdf_value = 0.0
