steady_state_residual = true
converged_residual_value = 1.0e-3
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
charge_exchange_frequency = 2.0
electron_charge_exchange_frequency = 0.0
nu_ei = 0.0
ionization_frequency = 2.0
#electron_ionization_frequency = 2.0
#ionization_energy = 1.0
constant_ionization_rate = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 5
#nelement = 32
nelement = 64
#nelement = 128
bc = "wall"
discretization = "chebyshev_pseudospectral"
element_spacing_option = "sqrt"

[vpa]
ngrid = 5
#nelement = 40
nelement = 80
L = 12.0 #8.0
bc = "zero"
discretization = "chebyshev_pseudospectral"
#discretization = "gausslegendre_pseudospectral"

[vz]
ngrid = 5
nelement = 80
L = 12.0
bc = "zero"
discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "boltzmann_electron_response"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[output]
ascii_output = true

[ion_numerical_dissipation]
#moment_dissipation_coefficient = 0.0001
#moment_dissipation_coefficient = 1.0
#vpa_dissipation_coefficient = 0.002
vpa_dissipation_coefficient = 0.1
#vpa_dissipation_coefficient = 0.2
#vpa_dissipation_coefficient = 2.0
#vpa_dissipation_coefficient = 20.0

[timestepping]
nstep = 1000000
#nstep = 1
dt = 1.0e-5
nwrite = 10000
nwrite_dfns = 10000

[electron_numerical_dissipation]

[neutral_numerical_dissipation]
