[reactions]
charge_exchange_frequency = 2.0
electron_charge_exchange_frequency = 0.0
ionization_frequency = 2.0
#electron_ionization_frequency = 2.0
ionization_energy = 1.0

[evolve_moments]
density = false
parallel_flow = false
parallel_pressure = false
moments_conservation = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 9
nelement = 16
#nelement = 32
#nelement = 64
bc = "wall"
discretization = "gausslegendre_pseudospectral"
element_spacing_option = "sqrt"

[vpa]
ngrid = 17
nelement = 10
#nelement = 20
L = 12.0 #8.0
bc = "zero"
discretization = "gausslegendre_pseudospectral"
#discretization = "gausslegendre_pseudospectral"

[vz]
ngrid = 17
nelement = 10
#nelement = 20
L = 8.0
bc = "zero"
discretization = "gausslegendre_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "kinetic_electrons"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[output]
ascii_output = true

[electron_numerical_dissipation]
#moment_dissipation_coefficient = 0.0001
#moment_dissipation_coefficient = 1.0
#vpa_dissipation_coefficient = 0.002
#vpa_dissipation_coefficient = 0.2
#vpa_dissipation_coefficient = 2.0
vpa_dissipation_coefficient = 20.0

[timestepping]
kinetic_electron_solver = "explicit_pseudotimestep"
nstep = 40000
#nstep = 1
dt = 0.0005
nwrite = 200
