steady_state_residual = true
converged_residual_value = 1.0e-3
charge_exchange_frequency = 2.0
electron_charge_exchange_frequency = 0.0
nu_ei = 0.0
ionization_frequency = 2.0
#electron_ionization_frequency = 2.0
#ionization_energy = 1.0
constant_ionization_rate = false

[evolve_moments]
density = false
parallel_flow = false
parallel_pressure = false
moments_conservation = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 5
#nelement = 32
nelement = 64
#nelement = 128
bc = "wall"
discretization = "chebyshev_pseudospectral"
element_spacing_option = "sqrt"

[vpa]
ngrid = 5
#nelement = 40
nelement = 80
L = 12.0 #8.0
bc = "zero"
discretization = "chebyshev_pseudospectral"
#discretization = "gausslegendre_pseudospectral"

[vz]
ngrid = 5
nelement = 80
L = 12.0
bc = "zero"
discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 1
electron_physics = "kinetic_electrons"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vz_IC_neutral_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[output]
#ascii_output = true

[electron_numerical_dissipation]
#moment_dissipation_coefficient = 0.0001
#moment_dissipation_coefficient = 1.0
#vpa_dissipation_coefficient = 0.002
#vpa_dissipation_coefficient = 0.2
vpa_dissipation_coefficient = 2.0
#vpa_dissipation_coefficient = 20.0

[timestepping]
nstep = 40000
#nstep = 1
dt = 5.0e-5
nwrite = 200
nwrite_dfns = 10000
type = "SSPRK4"

[electron_timestepping]
nstep = 5000000
#nstep = 1
dt = 2.0e-8
nwrite = 1000
nwrite_dfns = 1000
#type = "SSPRK4"
type = "Fekete4(3)"
minimum_dt = 1.0e-8
