# cheap input file for a 0D2V relaxation to a collisional Maxwellian distribution with self-ion collisions.
[reactions]
charge_exchange_frequency = 0.0
ionization_frequency = 0.0

[evolve_moments]
density = false
parallel_flow = false
moments_conservation = false
pressure = false

[z]
ngrid = 1
nelement = 1
nelement_local = 1
bc = "wall"
discretization = "chebyshev_pseudospectral"

[r]
ngrid = 1
nelement = 1
nelement_local = 1
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 5
nelement = 32
L = 8.485281374238571
bc = "zero"
discretization = "gausslegendre_pseudospectral"

[vperp]
ngrid = 5
nelement = 16
L = 4.242640687119286
discretization = "gausslegendre_pseudospectral"
# Fokker-Planck operator requires the "gausslegendre_pseudospectral
# options for the vpa and vperp grids

[composition]
n_ion_species = 1
n_neutral_species = 0
electron_physics = "boltzmann_electron_response"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 0.5
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0


[fokker_planck_collisions]
# nuii sets the normalised input C[F,F] Fokker-Planck collision frequency
nuii = 4.0
slowing_down_test = true
frequency_option = "manual"
use_fokker_planck = true

[timestepping]
nstep = 1000
dt = 7.0710678118654756e-6
nwrite = 50
nwrite_dfns = 50

[inner_r_bc_1]
bc = "periodic"

[outer_r_bc_1]
bc = "periodic"
