# cheap input file for a 0D2V relaxation to a collisional Maxwellian distribution with self-ion collisions.
[reactions]
charge_exchange_frequency = 0.0
ionization_frequency = 0.0

[evolve_moments]
density = false
parallel_flow = false
pressure = false
moments_conservation = false

[z]
ngrid = 1
nelement = 1
nelement_local = 1
bc = "wall"
discretization = "chebyshev_pseudospectral"

[r]
ngrid = 1
nelement = 1
nelement_local = 1
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 5
nelement = 8
L = 4.5
bc = "zero"
discretization = "gausslegendre_pseudospectral"

[vperp]
ngrid = 5
nelement = 4
L = 2.25
discretization = "gausslegendre_pseudospectral"
# Fokker-Planck operator requires the "gausslegendre_pseudospectral
# options for the vpa and vperp grids

[composition]
n_ion_species = 1
n_neutral_species = 0
electron_physics = "boltzmann_electron_response"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "directed-beam"
vpa0 = 0.0
vperp0 = 1.0
vth0 = 0.5

[fokker_planck_collisions]
use_fokker_planck = true
# nuii sets the normalised input C[F,F] Fokker-Planck collision frequency
nuii = 1.0
frequency_option = "manual"
boundary_data_option="delta_f_multipole"
#boundary_data_option="direct_integration"

[timestepping]
nstep = 500
dt = 1.0e-3
nwrite = 1
nwrite_dfns = 1
implicit_ion_advance = true
type = "KennedyCarpenterARK324"

[nonlinear_solver]
nonlinear_max_iterations = 20
rtol = 1.0e-5
atol = 1.0e-12
linear_restart = 10
total_its_soft_limit = 50
preconditioner_update_interval = 300
 
