[ion_source]
z_profile = "constant"
source_strength = 0.05
source_T = 0.25

[evolve_moments]
density = false
parallel_flow = false
parallel_pressure = false
moments_conservation = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 5
nelement = 16
bc = "wall"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 5
nelement = 16
L = 6.0
bc = "zero"
discretization = "chebyshev_pseudospectral"

[vperp]
ngrid = 5
nelement = 8
L = 3.0
bc = "zero"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 9
nelement = 64
L = 18.0
bc = "both_zero"
discretization = "chebyshev_pseudospectral"

[composition]
n_ion_species = 1
n_neutral_species = 0
electron_physics = "boltzmann_electron_response"
T_e = 1.0
T_wall = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.0

[z_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 1.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[vpa_IC_ion_species_1]
initialization_option = "gaussian"
density_amplitude = 1.0
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[ion_numerical_dissipation]
vpa_dissipation_coefficient = 1.0e-3 #1.0e-2 #1.0e-1
vperp_dissipation_coefficient = 1.0e-3 #1.0e-2 #1.0e-1
force_minimum_pdf_value = 0.0

[geometry]
option="1D-mirror"
DeltaB=0.5
#option="constant-helical"
pitch=1.0
rhostar= 1.0

[timestepping]
nstep = 10000
dt = 1.0e-3
nwrite = 50
nwrite_dfns = 50
