[composition]
n_ion_species = 1
n_neutral_species = 1
T_e = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 0.16666666666666666

[neutral_species_1]
initial_density = 1.0
initial_temperature = 0.16666666666666666

[z_IC_ion_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
density_amplitude = 0.001
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[reactions]
ionization_frequency = 0.0
charge_exchange_frequency = [0.0, 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.3, 3.6, 3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6.0, 6.3]

[evolve_moments]
density = false
parallel_flow = false
moments_conservation = true
pressure = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 17
nelement = 2
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 17
nelement = 8
L = 8.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 17
nelement = 8
L = 8.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 2500
dt = 0.002
nwrite = 20
split_operators = false
