[composition]
n_ion_species = 1
n_neutral_species = 1
T_e = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 1.3333333333333333

[neutral_species_1]
initial_density = 1.0
initial_temperature = 1.3333333333333333

[z_IC_ion_species_1]
initialization_option = "sinusoid"
#density_amplitude = 0.001
density_amplitude = 0.01
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
#density_amplitude = 0.001
density_amplitude = 0.01
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[reactions]
ionization_frequency = 0.0
charge_exchange_frequency = [0.0, 0.6, 1.2, 1.8, 2.4, 3.0, 3.6, 4.2, 4.8, 5.4, 6.0, 6.6, 7.2, 7.8, 8.4, 9.0, 9.6, 10.2, 10.8, 11.4, 12.0, 12.6, 13.2, 13.8, 14.4, 15.0, 15.6, 16.2, 16.8, 17.4, 18.0]

[evolve_moments]
density = true
parallel_flow = true
moments_conservation = true
pressure = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 17
nelement = 2
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 17
nelement = 8
L = 14.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 17
nelement = 8
L = 14.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 3000
dt = 0.00075
nwrite = 20
#nwrite_dfns = 20 #80
split_operators = false
