[composition]
n_ion_species = 1
n_neutral_species = 1
T_e = 1.0

[ion_species_1]
initial_density = 1.0
initial_temperature = 0.6666666666666666

[neutral_species_1]
initial_density = 1.0
initial_temperature = 0.6666666666666666

[z_IC_ion_species_1]
initialization_option = "sinusoid"
#density_amplitude = 0.001
density_amplitude = 0.01
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[z_IC_neutral_species_1]
initialization_option = "sinusoid"
#density_amplitude = 0.001
density_amplitude = 0.01
density_phase = 0.0
upar_amplitude = 0.0
upar_phase = 0.0
temperature_amplitude = 0.0
temperature_phase = 0.0

[reactions]
ionization_frequency = 0.0
charge_exchange_frequency = [0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0, 4.4, 4.8, 5.2, 5.6, 6.0, 6.4, 6.8, 7.2, 7.6, 8.0, 8.4, 8.8, 9.2, 9.6, 10.0, 10.4, 10.8, 11.2, 11.6, 12.0]

[evolve_moments]
density = false
parallel_flow = false
moments_conservation = true
pressure = false

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 17
nelement = 2
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 17
nelement = 8
L = 16.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 17
nelement = 8
L = 16.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 1800
dt = 0.001
nwrite = 20
split_operators = false
