#runtime_plots = true
n_ion_species = 1
n_neutral_species = 1
electron_physics = "kinetic_electrons"
evolve_moments_density = false
evolve_moments_parallel_flow = false
evolve_moments_parallel_pressure = false
evolve_moments_conservation = false
recycling_fraction = 0.5
T_e = 0.2 # 1.0
T_wall = 0.1
initial_density1 = 1.0
initial_temperature1 = 1.0
z_IC_option1 = "gaussian"
z_IC_density_amplitude1 = 0.001
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 1.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
vpa_IC_option1 = "gaussian"
vpa_IC_density_amplitude1 = 1.0
vpa_IC_density_phase1 = 0.0
vpa_IC_upar_amplitude1 = 0.0
vpa_IC_upar_phase1 = 0.0
vpa_IC_temperature_amplitude1 = 0.0
vpa_IC_temperature_phase1 = 0.0
initial_density2 = 1.0
initial_temperature2 = 1.0
z_IC_option2 = "gaussian"
z_IC_density_amplitude2 = 0.001
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = -1.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
vpa_IC_option2 = "gaussian"
vpa_IC_density_amplitude2 = 1.0
vpa_IC_density_phase2 = 0.0
vpa_IC_upar_amplitude2 = 0.0
vpa_IC_upar_phase2 = 0.0
vpa_IC_temperature_amplitude2 = 0.0
vpa_IC_temperature_phase2 = 0.0
charge_exchange_frequency = 0.75
ionization_frequency = 0.5
constant_ionization_rate = false
r_ngrid = 1
r_nelement = 1
z_ngrid = 5
z_nelement = 32
z_bc = "wall"
z_discretization = "chebyshev_pseudospectral"
#z_element_spacing_option = "sqrt"
vpa_ngrid = 6
vpa_nelement = 63
vpa_L = 36.0
vpa_bc = "zero"
vpa_discretization = "chebyshev_pseudospectral"
vz_ngrid = 6
vz_nelement = 63
vz_L = 36.0
vz_bc = "zero"
vz_discretization = "chebyshev_pseudospectral"

[timestepping]
type = "SSPRK4"
#nstep = 50000
nstep = 50000
dt = 1.0e-3
nwrite = 1000
nwrite_dfns = 1000
steady_state_residual = true
#converged_residual_value = 1.0e-3

[electron_timestepping]
nstep = 5000000
#nstep = 1
dt = 2.0e-6
nwrite = 10000
nwrite_dfns = 10000
type = "SSPRK4"
#type = "Fekete4(3)"
rtol = 1.0e-3
#minimum_dt = 1.0e-8
initialization_residual_value = 2.5
converged_residual_value = 0.1 #1.0e-3

[ion_source]
active = true
z_profile = "gaussian"
z_width = 0.125
source_strength = 2.0
source_T = 2.0

[ion_numerical_dissipation]
#vpa_dissipation_coefficient = 1.0e-1
#vpa_dissipation_coefficient = 1.0e-2
#vpa_dissipation_coefficient = 1.0e-3
#force_minimum_pdf_value = 0.0

[electron_numerical_dissipation]
#vpa_dissipation_coefficient = 2.0
#force_minimum_pdf_value = 0.0

[neutral_numerical_dissipation]
#vz_dissipation_coefficient = 1.0e-1
#vz_dissipation_coefficient = 1.0e-2
#vz_dissipation_coefficient = 1.0e-3
#force_minimum_pdf_value = 0.0

[krook_collisions]
use_krook = false

[maxwell_diffusion_collisions]
use_maxwell_diffusion = false
#D_ee = 10.0
#D_ii = 0.1
#diffusion_coefficient_option = "manual"
