test_type = "Fokker-Planck collisions"

# default input for test
test_input_full_f = Dict(
     "run_name" => "full_f",
     "timestepping" => Dict{String,Any}("dt" => 0.0,
                                        "nstep" => 3,
                                        "nwrite" => 2,
                                        "nwrite_dfns" => 2),
     "Bmag" => 1.0,
     "Bzed" => 1.0,
     "T_e" => 1.0,
     "T_wall" => 1.0,
     "electron_physics" => "boltzmann_electron_response",
     "evolve_moments_conservation" => false,
     "evolve_moments_density" => false,
     "evolve_moments_parallel_flow" => false,
     "evolve_moments_parallel_pressure" => false,
     "initial_density1" => 0.5,
     "initial_density2" => 0.5,
     "initial_temperature1" => 1.0,
     "initial_temperature2" => 1.0,
     "charge_exchange_frequency" => 0.0,
     "ionization_frequency" => 0.0,
     "constant_ionization_rate" => false,
     "n_ion_species" => 1,
     "n_neutral_species" => 0,
     "nuii" => 1.0,
     "r_bc" => "periodic",
     "r_discretization" => "chebyshev_pseudospectral",
     "r_nelement" => 1,
     "r_ngrid" => 3,
     "rhostar" => 1.0,
     "split_operators" => false,
     "vpa_L" => 6.0,
     "vpa_bc" => "zero",
     "vpa_discretization" => "gausslegendre_pseudospectral",
     "vpa_nelement" => 2,
     "vpa_ngrid" => 3,
     "vperp_L" => 3.0,
     "vperp_discretization" => "gausslegendre_pseudospectral",
     "vperp_nelement" => 2,
     "vperp_ngrid" => 3,
     "z_IC_density_amplitude1" => 0.001,
     "z_IC_density_amplitude2" => 0.001,
     "z_IC_density_phase1" => 0.0,
     "z_IC_density_phase2" => 0.0,
     "z_IC_option1" => "sinusoid",
     "z_IC_option2" => "sinusoid",
     "z_IC_temperature_amplitude1" => 0.0,
     "z_IC_temperature_amplitude2" => 0.0,
     "z_IC_temperature_phase1" => 0.0,
     "z_IC_temperature_phase2" => 0.0,
     "z_IC_upar_amplitude1" => 0.0,
     "z_IC_upar_amplitude2" => 0.0,
     "z_IC_upar_phase1" => 0.0,
     "z_IC_upar_phase2" => 0.0,
     "z_bc" => "wall",
     "z_discretization" => "chebyshev_pseudospectral",
     "z_nelement" => 1,
     "z_ngrid" => 3,
    )

test_input_list = [
     test_input_full_f ,
    ]
