test_type = "Fokker-Planck collisions"

# default input for test
test_input_full_f = Dict(
     "run_name" => "full_f",
     "timestepping" => Dict{String,Any}("dt" => 0.0,
                                        "nstep" => 3,
                                        "nwrite" => 2,
                                        "nwrite_dfns" => 2),
     "composition" => Dict{String,Any}("n_ion_species" => 1,
                                       "n_neutral_species" => 0,
                                       "T_e" => 1.0,
                                       "T_wall" => 1.0,
                                       "electron_physics" => "boltzmann_electron_response"),
     "evolve_moments_conservation" => false,
     "evolve_moments_density" => false,
     "evolve_moments_parallel_flow" => false,
     "evolve_moments_parallel_pressure" => false,
     "ion_species_1" => Dict{String,Any}("initial_density" => 0.5,      
                                         "initial_temperature" => 1.0)
     "z_IC_ion_species_1" => Dict{String,Any}("density_amplitude" => 0.001,
                                              "density_phase" => 0.0,
                                              "initialization_option1" => "sinusoid",
                                              "temperature_amplitude" => 0.0,
                                              "temperature_phase" => 0.0,
                                              "upar_amplitude" => 0.0,
                                              "upar_phase" => 0.0),     
     "charge_exchange_frequency" => 0.0,
     "ionization_frequency" => 0.0,
     "constant_ionization_rate" => false,
     "fokker_planck_collisions" => Dict{String,Any}("use_fokker_planck" => true,
                                                    "nuii" => 1.0,
                                                    "frequency_option" => "manual"),
     "r_bc" => "periodic",
     "r_discretization" => "chebyshev_pseudospectral",
     "r_nelement" => 1,
     "r_ngrid" => 3,
     "vpa_L" => 6.0,
     "vpa_bc" => "zero",
     "vpa_discretization" => "gausslegendre_pseudospectral",
     "vpa_nelement" => 2,
     "vpa_ngrid" => 3,
     "vperp_L" => 3.0,
     "vperp_discretization" => "gausslegendre_pseudospectral",
     "vperp_nelement" => 2,
     "vperp_ngrid" => 3,
     "z_bc" => "wall",
     "z_discretization" => "chebyshev_pseudospectral",
     "z_nelement" => 1,
     "z_ngrid" => 3,
    )

test_input_list = [
     test_input_full_f ,
    ]
