test_type = "gyroaverage"

# default inputs for tests
test_input = Dict(
    "run_name" => "gyroaverage",
    "composition" => Dict("n_ion_species" => 1,
                          "n_neutral_species" => 0,
                          "gyrokinetic_ions" => true,
                          "T_e" => 1.0,
                          "T_wall" => 1.0),
    "evolve_moments_density" => false,
    "evolve_moments_parallel_flow" => false,
    "evolve_moments_parallel_pressure" => false,
    "evolve_moments_conservation" => false,
    "ion_species_1" => Dict("initial_density" => 1.0,
                            "initial_temperature" => 1.0),
    "z_IC_ion_species_1" => Dict("initialization_option" => "gaussian",
                                 "density_amplitude" => 0.001,
                                 "density_phase" => 0.0,
                                 "upar_amplitude" => 1.0,
                                 "upar_phase" => 0.0,
                                 "temperature_amplitude" => 0.0,
                                 "temperature_phase" => 0.0),
    "vpa_IC_ion_species_1" => Dict("initialization_option" => "gaussian",
                                 "density_amplitude" => 1.0,
                                 "density_phase" => 0.0,
                                 "upar_amplitude" => 0.0,
                                 "upar_phase" => 0.0,
                                 "temperature_amplitude" => 0.0,
                                 "temperature_phase" => 0.0),
    "charge_exchange_frequency" => 0.0,
    "ionization_frequency" => 0.05,
    "constant_ionization_rate" => true,
    "timestepping" => Dict{String,Any}("nstep" => 3,
                                       "dt" => 1.0e-12,
                                       "nwrite" => 2,
                                       "nwrite_dfns" => 2,),
    "r_ngrid" => 5,
    "r_nelement" => 2,
    "r_bc" => "periodic",
    "z_ngrid" => 5,
    "z_nelement" => 2,
    "z_bc" => "periodic",
    "z_discretization" => "chebyshev_pseudospectral",
    "vpa_ngrid" => 5,
    "vpa_nelement" => 2,
    "vpa_L" => 6.0,
    "vpa_bc" => "zero",
    "vpa_discretization" => "chebyshev_pseudospectral",
    "vperp_ngrid" => 5,
    "vperp_nelement" => 1,
    "vperp_L" => 3.0,
    "vperp_bc" => "zero",
    "vperp_discretization" => "chebyshev_pseudospectral",
    "vz_ngrid" => 5,
    "vz_nelement" => 2,
    "vz_L" => 6.0,
    "vz_bc" => "zero",
    "vz_discretization" => "chebyshev_pseudospectral",
    "numerical_dissipation" => Dict("vpa_dissipation_coefficient" => 1.0e-3,
                                    "vperp_dissipation_coefficient" => 1.0e-3),
    "geometry" => Dict("DeltaB"=>0.0,
                       "option"=>"constant-helical",
                       "pitch"=>0.1,
                       "rhostar"=> 0.1),
)

test_input_list = [
     test_input,
    ]
