test_type = "Kinetic electron"
using moment_kinetics.type_definitions: OptionsDict

test_input = OptionsDict("composition" => OptionsDict("n_ion_species" => 1,
                                                      "n_neutral_species" => 1,
                                                      "electron_physics" => "kinetic_electrons",
                                                      "recycling_fraction" => 0.5,
                                                      "T_e" => 0.2,
                                                      "T_wall" => 0.1),
                         "run_name" => "kinetic_electron",
                         "base_directory" => test_output_directory,
                         "evolve_moments_density" => true,
                         "evolve_moments_parallel_flow" => true,
                         "evolve_moments_parallel_pressure" => true,
                         "evolve_moments_conservation" => true,
                         "ion_species_1" => OptionsDict("initial_density" => 1.0,
                                                        "initial_temperature" => 1.0),
                         "z_IC_ion_species_1" => OptionsDict("initialization_option" => "gaussian",
                                                             "density_amplitude" => 0.001,
                                                             "density_phase" => 0.0,
                                                             "upar_amplitude" => 1.0,
                                                             "upar_phase" => 0.0,
                                                             "temperature_amplitude" => 0.0,
                                                             "temperature_phase" => 0.0),
                         "vpa_IC_ion_species_1" => OptionsDict("initialization_option" => "gaussian",
                                                               "density_amplitude" => 1.0,
                                                               "density_phase" => 0.0,
                                                               "upar_amplitude" => 0.0,
                                                               "upar_phase" => 0.0,
                                                               "temperature_amplitude" => 0.0,
                                                               "temperature_phase" => 0.0),
                         "neutral_species_1" => OptionsDict("initial_density" => 1.0,
                                                            "initial_temperature" => 1.0),
                         "z_IC_neutral_species_1" => OptionsDict("initialization_option" => "gaussian",
                                                                 "density_amplitude" => 0.001,
                                                                 "density_phase" => 0.0,
                                                                 "upar_amplitude" => -1.0,
                                                                 "upar_phase" => 0.0,
                                                                 "temperature_amplitude" => 0.0,
                                                                 "temperature_phase" => 0.0),
                         "vz_IC_neutral_species_1" => OptionsDict("initialization_option" => "gaussian",
                                                                  "density_amplitude" => 1.0,
                                                                  "density_phase" => 0.0,
                                                                  "upar_amplitude" => 0.0,
                                                                  "upar_phase" => 0.0,
                                                                  "temperature_amplitude" => 0.0,
                                                                  "temperature_phase" => 0.0),
                         "charge_exchange_frequency" => 0.75,
                         "ionization_frequency" => 0.5,
                         "constant_ionization_rate" => false,
                         "timestepping" => OptionsDict("type" => "Fekete4(3)",
                                                       "nstep" => 3,
                                                       "dt" => 2.0e-8,
                                                       "minimum_dt" => 1.0e-8,
                                                       "CFL_prefactor" => 1.0,
                                                       "step_update_prefactor" => 0.4,
                                                       "nwrite" => 2,
                                                       "split_operators" => false),
                         "electron_timestepping" => OptionsDict("type" => "Fekete4(3)",
                                                                "nstep" => 10,
                                                                "dt" => 4.0e-11,
                                                                "minimum_dt" => 2.0e-11,
                                                                "initialization_residual_value" => 1.e10,
                                                                "converged_residual_value" => 1.e10,
                                                                "nwrite" => 10000,
                                                                "nwrite_dfns" => 10000,
                                                                "no_restart" => true),
                         "r" => OptionsDict("ngrid" => 1,
                                            "nelement" => 1),
                         "z" => OptionsDict("ngrid" => 3,
                                            "nelement" => 24,
                                            "bc" => "wall",
                                            "discretization" => "chebyshev_pseudospectral",
                                            "element_spacing_option" => "sqrt"),
                         "vpa" => OptionsDict("ngrid" => 3,
                                              "nelement" => 16,
                                              "L" => 6.0,
                                              "bc" => "zero",
                                              "discretization" => "chebyshev_pseudospectral"),
                         "vz" => OptionsDict("ngrid" => 3,
                                             "nelement" => 6,
                                             "L" => 6.0,
                                             "bc" => "zero",
                                             "discretization" => "chebyshev_pseudospectral"),
                         "ion_source" => OptionsDict("active" => true,
                                                     "z_profile" => "gaussian",
                                                     "z_width" => 0.125,
                                                     "source_strength" => 2.0,
                                                     "source_T" => 2.0),
                         "krook_collisions" => OptionsDict("use_krook" => true),
                         "numerical_dissipation" => OptionsDict("force_minimum_pdf_value" => 0.0,
                                                                "vpa_dissipation_coefficient" => 1e-2))


test_input_list = [
     test_input,
    ]
