test_type = "MMS"

# default inputs for tests
test_input = Dict(
    "manufactured_solns" => Dict("use_for_advance"=>true),
    "evolve_moments_density" => false,
    "evolve_moments_parallel_flow" => false,
    "evolve_moments_parallel_pressure" => false,
    "evolve_moments_conservation" => false,
    "composition" => Dict("n_ion_species" => 1,
                          "n_neutral_species" => 1,
                          "electron_physics" => "boltzmann_electron_response",
                          "T_e" => 1.0,
                          "T_wall" => 1.0),    
    "run_name" => "MMS-2D-wall_cheb-with-neutrals",
    "charge_exchange_frequency" => 0.0,
    "ionization_frequency" => 0.0,
    "timestepping" => Dict{String,Any}("nstep" => 3,
                                       "dt" => 1.e-8,
                                       "nwrite" => 2,
                                       "type" => "SSPRK2",
                                       "split_operators" => false),
    "z_ngrid" => 3,
    "z_nelement" => 2,
    "z_bc" => "wall",
    "z_discretization" => "chebyshev_pseudospectral",
    "r_ngrid" => 3,
    "r_nelement" => 2,
    "r_bc" => "periodic",
    "r_discretization" => "chebyshev_pseudospectral",
    "vpa_ngrid" => 3,
    "vpa_nelement" => 2,
    "vpa_L" => 12.0,
    "vpa_bc" => "periodic",
    "vpa_discretization" => "chebyshev_pseudospectral",
    "vperp_ngrid" => 3,
    "vperp_nelement" => 2,
    "vperp_L" => 6.0,
    "vperp_discretization" => "chebyshev_pseudospectral",
    "vz_ngrid" => 3,
    "vz_nelement" => 2,
    "vz_L" => 12.0,
    "vz_bc" => "none",
    "vz_discretization" => "chebyshev_pseudospectral",
    "vr_ngrid" => 3,
    "vr_nelement" => 2,
    "vr_L" => 12.0,
    "vr_bc" => "none",
    "vr_discretization" => "chebyshev_pseudospectral",
    "vzeta_ngrid" => 3,
    "vzeta_nelement" => 2,
    "vzeta_L" => 12.0,
    "vzeta_bc" => "none",
    "vzeta_discretization" => "chebyshev_pseudospectral",
    "geometry" => Dict{String,Any}("rhostar" => 1.0,),
)

test_input_list = [
     test_input,
    ]
