#combine_outer = ["charge_exchange_frequency"]
n_ion_species = 1
n_neutral_species = 1
boltzmann_electron_response = true
T_e = 1.0
initial_density1 = 1.0
initial_temperature1 = 4.0
initial_density2 = 1.0
initial_temperature2 = 4.0
z_IC_option1 = "sinusoid"
#z_IC_density_amplitude1 = 0.001
z_IC_density_amplitude1 = 0.01
z_IC_density_phase1 = 0.0
z_IC_upar_amplitude1 = 0.0
z_IC_upar_phase1 = 0.0
z_IC_temperature_amplitude1 = 0.0
z_IC_temperature_phase1 = 0.0
z_IC_option2 = "sinusoid"
#z_IC_density_amplitude2 = 0.001
z_IC_density_amplitude2 = 0.01
z_IC_density_phase2 = 0.0
z_IC_upar_amplitude2 = 0.0
z_IC_upar_phase2 = 0.0
z_IC_temperature_amplitude2 = 0.0
z_IC_temperature_phase2 = 0.0
charge_exchange_frequency = [0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0, 4.4, 4.8, 5.2, 5.6, 6.0, 6.4, 6.8, 7.2, 7.6, 8.0, 8.4, 8.8, 9.2, 9.6, 10.0, 10.4, 10.8, 11.2, 11.6, 12.0, 12.4]
ionization_frequency = 0.0

[evolve_moments]
density = false
parallel_flow = false
parallel_pressure = false
moments_conservation = true

[r]
ngrid = 1
nelement = 1

[z]
ngrid = 17
nelement = 2
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vpa]
ngrid = 17
nelement = 8
L = 16.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[vz]
ngrid = 17
nelement = 8
L = 16.0
bc = "periodic"
discretization = "chebyshev_pseudospectral"

[timestepping]
nstep = 3000
dt = 1.0e-3
nwrite = 20
#nwrite_dfns = 20 #80
n_rk_stages = 4
split_operators = false
