# Based on example from https://github.com/julia-actions/julia-runtest
name: Check examples

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  contents: read

jobs:
  examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
      - uses: julia-actions/cache@v2
      - name: Test examples
        run: |
          touch Project.toml
          julia -O3 --project -e 'import Pkg; Pkg.develop(path="moment_kinetics/"); Pkg.add("NCDatasets"); Pkg.precompile()'
          julia -O3 --project examples/runtests.jl
