# Run all tests, which can take a long time
name: Long tests

# Only run when commits are added to master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'moment_kinetics/'
      # The following is copied and simplified from
      # https://github.com/julia-actions/julia-runtest/blob/master/action.yml
      # in order to pass customised arguments to `Pkg.test()`
      - run: |
          julia --color=yes --depwarn=yes --project=moment_kinetics/ -e 'import Pkg; Pkg.test(; test_args=["--ci", "--long", "--force-optional-dependencies"], julia_args=["--check-bounds=auto"])'
        shell: bash
